# Generated by Django 3.2 on 2021-04-08 13:47

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="column",
            name="schema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="generator.schema",
            ),
        ),
    ]
